# Generated by Django 5.0.4 on 2024-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_animal_information_animal_is_rare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('anseriformes', 'Гусеобразные'), ('galliformes', 'Курообразные')], default='galliformes', max_length=100, verbose_name='Вид')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Популяция')),
                ('is_rare', models.BooleanField(default=False, verbose_name='Вымирающая птица')),
            ],
            options={
                'verbose_name': 'Птица',
                'verbose_name_plural': 'Птицы',
            },
        ),
        migrations.DeleteModel(
            name='Insects',
        ),
    ]
