# Generated by Django 5.0.4 on 2024-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_alter_news_options_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('mamal', 'Млекопитающее'), ('fish', 'Рыба'), ('reptile', 'Рептилия')], default='mammal', max_length=100, verbose_name='Род')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Популяция')),
                ('is_rare', models.BooleanField(default=False, verbose_name='Вымирающее животное')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('anseriformes', 'Гусеобразные'), ('galliformes', 'Курообразные')], default='galliformes', max_length=100, verbose_name='Вид')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Популяция')),
                ('is_rare', models.BooleanField(default=False, verbose_name='Вымирающая птица')),
            ],
            options={
                'verbose_name': 'Птица',
                'verbose_name_plural': 'Птицы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firat_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Фото сотрудника')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
